version: '3.8'

services:
  app:
    image: library-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db_pg_15:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432

